apiVersion: mqttbroker.iotoperations.azure.com/v1beta1
kind: BrokerListener
metadata:
  name: dev-az-mqtt-non-tls-listener
  namespace: azure-iot-operations
spec:
  brokerRef: broker
  serviceType: loadBalancer
  serviceName: dev-aio-mq-non-tls
  ports:
  - port: 1883
    protocol: Mqtt