{
 "title": "AIO Sample Dashboard",
 "description": "Sample dashboard for viewing Azure IoT Operations health and usage",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "query_result(max by(cluster)(max_over_time(up{job=\"kube-state-metrics\"}[$__range])))"
    }
   },
   { "name": "namespace", "query": "azure-iot-operations" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "cluster",
   "options": {
    "content": "<div style=\"background-color:black; text-align: center\"> \n  <span style=\"color:#C1C9D1; font-size:16px\">[$cluster]</span>\n</div>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 2 },
   "repeat": "cluster",
   "options": {
    "content": "<div style=\"background-color:#C1C9D1; text-align: center\"> \n  <span style=\"color:black; font-size:16px\">AIO Health Model</span>\n</div>\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "AIO Service Health [$cluster]",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "label_replace(min(\r\n  # NEW Broker\r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_broker_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Authentication failures\",\"\",\"\") or\r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_broker_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_broker_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Authorization failures\",\"\",\"\") or        \r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_broker_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_broker_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Backpressure\",\"\",\"\") or\r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_broker_qos0_messages_dropped{pod_type=\"BE\",cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_broker_qos0_messages_dropped{pod_type=\"BE\",cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Dropped QoS0 Msgs\",\"\",\"\") or\r\n  label_replace(\r\n    0 * max(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"aio-broker-upgrade-status-job.*\", phase=~\"failed\"} == 1) or\r\n    1 * max(kube_job_status_succeeded{cluster=\"$cluster\", namespace=~\"$namespace\", job_name=~\"aio-broker-upgrade-status-job.*\"} == 1) or vector(404)\r\n    ,\"_\",\"Upgrade failures\",\"\",\"\") or  \r\n  # Old Broker (MQ)\r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_mq_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_mq_authentication_failures{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Authentication failures\",\"\",\"\") or\r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_mq_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_mq_authorization_deny{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Authorization failures\",\"\",\"\") or        \r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_mq_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_mq_backpressure_packets_rejected{cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Backpressure\",\"\",\"\") or\r\n  label_replace(min(\r\n    0 * sgn(sum(rate(aio_mq_qos0_messages_dropped{pod_type=\"BE\",cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) > 0) or\r\n    1 * sgn(sum(rate(aio_mq_qos0_messages_dropped{pod_type=\"BE\",cluster=\"$cluster\", instance=~\"$namespace\"}[2m])) ) or\r\n    vector(0)>0)\r\n    ,\"_\",\"Dropped QoS0 Msgs\",\"\",\"\") or\r\n  vector(404) # Tail; not shown\r\n),\"_\",\"Broker\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n    0 * sgn(count (0 <\r\n        rate(aio_opc_mqtt_message_publishing_duration_count{\r\n            cluster=\"$cluster\",aio_opc_mqtt_publish_result!~\"(success|nomatchingsubscribers)\"\r\n        }[5m:1m])\r\n    )) or\r\n    0 * sgn(count (0 <\r\n        rate(aio_opc_session_connect_duration_count{\r\n            cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_connect_result!=\"success\"\r\n        }[5m:1m])\r\n    )) or\r\n    sgn(0 < count( # Healthy activity\r\n        rate(aio_opc_mqtt_message_publishing_duration_count{\r\n            cluster=\"$cluster\",aio_opc_mqtt_publish_result=~\"(success|nomatchingsubscribers)\"\r\n        }[5m:1m]))\r\n    ) or\r\n    vector(0)>0 or vector(404)\r\n),\"_\",\"Connectors\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(min(\r\n    0 * (count(0 < rate(aio_dataflow_errors{cluster='$cluster'}[5m:1m]))) or # Errors\r\n    1 * sgn(count(0 < rate(aio_dataflow_messages_sent{cluster='$cluster'}[5m:1m]))) or # Activity\r\n    vector(0) > 0 or vector(404)\r\n),\"_\",\"Dataflows\",\"\",\"\") ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Errors [$cluster]",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "# NEW BROKER:\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_broker_authentication_failures{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:authn_failure','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_broker_authorization_deny{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:authz_deny','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_broker_backpressure_packets_rejected{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:backpressure_rejected','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_broker_qos0_messages_dropped{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:qos0_msgs_dropped','','')) or\r\n# OLD BROKER:\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_mq_authentication_failures{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:authn_failure','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_mq_authorization_deny{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:authz_deny','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_mq_backpressure_packets_rejected{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:backpressure_rejected','','')) or\r\nsum by(_)(label_replace(\r\n        0 < increase(aio_mq_qos0_messages_dropped{cluster=\"$cluster\",namespace=~\"$namespace\"}[5m:1m])\r\n    ,'_','Broker:qos0_msgs_dropped','','')) or\r\nvector(0)>0 #",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(_)(label_replace(\r\n        increase(aio_opc_mqtt_message_publishing_duration_count{\r\n            cluster=\"$cluster\",aio_opc_mqtt_publish_result!~\"(success|nomatchingsubscribers)\"\r\n        }[5m:1m])\r\n    ,'_','Connector:publishError:$1','aio_opc_mqtt_publish_result','(.*)')) or\r\nsum by (_)(label_replace(\r\n        increase(aio_opc_session_connect_duration_count{\r\n            cluster=\"$cluster\",aio_opc_module_type=\"opcua-connector\",aio_opc_connect_result!=\"success\"\r\n        }[5m:1m])\r\n    ,'_','Connector:connectError:$1','aio_opc_connect_result','(.*)')) or\r\nvector(0)>0 ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (_)(\r\n    label_replace(increase(aio_dataflow_errors{cluster='$cluster'}[5m:1m]),'_','Dataflows:$1','errorcode','(.*)')\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AIO Kubernetes Workload Health [$cluster]",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "## Workload Readiness health\r\n############################\r\nlabel_replace(min(\r\navg(label_join( # Workload ready percents (for deployment, daemonset, and statefulset)\r\n    label_replace(label_join(\r\n        kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\"$namespacem\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n  / label_replace(label_join(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=~\"$namespace\"} or\r\n        kube_statefulset_status_replicas{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_(status|spec)_.*\")\r\n  ,\"workload\", \":\", \"workloadType\", \"workloadName\")\r\n) by (workload) >=0 \r\n) or vector(404),\"_\",\"AIO Workload Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Restart Health:\r\n############################\r\nlabel_replace(\r\n  sgn(sum_over_time(sum(rate(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}[10m:1m]\r\n    )*60)[1h:]) > 5) * 0.0 # RED: Cumulative restarts over X(5) time greater than Y(1h)\r\n  or sgn(max(\r\n    kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\"}\r\n    + 1 >= 0))\r\n  ,\"_\",\"AIO Container Restarts\",\"\",\"\")\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container CPU top-level health\r\n################################\r\nlabel_replace(\r\nmin(sgn( # Check for throttling > N indicating container is exceeding its CPU limits\r\n      rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m]) \r\n    / rate(container_cpu_cfs_periods_total{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}[10m])\r\n    >= 0.80)\r\n    ) \r\n    * 0.0\r\nor\r\nmin(\r\n    sgn(min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"cpu\"}) by (namespace,container))\r\n    )\r\n,\"_\",\"AIO Container CPU\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "## Container Memory Health:\r\n###########################\r\nlabel_replace(\r\nmin( # Look for high memory utilization\r\n    0.0 * sgn((\r\n        max(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\"}) by (namespace,container)\r\n      / min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace, container)\r\n    ) >= .95) or # show health state of 0 if container memory utilization >= 95%\r\n    vector(0)>0\r\n)\r\nor\r\nmin(\r\n    sgn(min(kube_pod_container_resource_limits{cluster=\"$cluster\",namespace=~\"$namespace\",container!=\"\",resource=\"memory\"}) by (namespace,container))\r\n)\r\n,\"_\",\"AIO Container Memory\",\"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AIO K8s Workload Details [$cluster]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "label_replace(sum (\r\n    label_replace(label_join(\r\n        kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*\"} or\r\n        kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\".*\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n),\"_\",\"Ready\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "label_replace(\r\n    sum(\r\n        kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*\"} or\r\n        kube_deployment_spec_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\".*\"} or\r\n        kube_statefulset_status_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*\"}\r\n    ) - sum (\r\n    label_replace(label_join(\r\n        kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*\"} or\r\n        kube_deployment_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\".*\"} or\r\n        kube_statefulset_status_replicas_ready{cluster=\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*\"}\r\n        ,\"workloadName\", \"\", \"deployment\", \"daemonset\", \"replicaset\", \"statefulset\")\r\n        ,\"workloadType\", \"$1\", \"__name__\", \"kube_(.*)_status_.*\")\r\n),\"_\",\"NOT-Ready\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "# Container Restarts\r\nlabel_replace(ceil(sum(increase(kube_pod_container_status_restarts_total{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\".*\"}[$__rate_interval]))),\"_\",\"Restarts\",\"\",\"\") > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "(label_replace(sum(rate(container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\".*\",container!=\"\"}[$__rate_interval]))*1000,\"_\",\"CPU Usage (milli-cores)\",\"\",\"\") )\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(label_replace(sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\".*\",container!=\"\"})/(1024*1024),\"_\",\"Mem Working Bytes (MB)\",\"\",\"\") )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kubernetes Node Health [$cluster]",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 25 },
   "repeat": "cluster",
   "targets": [
    {
     "expr": "# Node Health Status\r\n####################\r\nlabel_replace(\r\n  sum(\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition=\"ready\",status=\"false\"} > 0) * 0 or\r\n    max by (node) (kube_node_status_condition{cluster=\"$cluster\",condition=\"ready\",status=\"true\"} > 0) * 1\r\n  ) / sum(kube_node_info{cluster=\"$cluster\"})\r\n  ,\"_\",\"Node Readiness\",\"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Node CPU Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        100 - ((avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"idle\"}[5m])) \r\n              + avg by (instance) (rate(node_cpu_seconds_total{cluster=\"$cluster\",mode=\"iowait\"}[5m]))\r\n        ) * 100) > 90)\r\n    or 1.0 * sgn(sum by (instance)(node_cpu_seconds_total{cluster=\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n    ,\"_\",\"$1\",\"instance\",\"(.*)\"))\r\n# END inner query\r\n),\"_\",\"Node CPU\", \"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Node Memory Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(_)(label_replace(vector(0)>0\r\n    or 0.0 * sgn(\r\n        (100 * sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - (node_memory_MemFree_bytes{cluster=\"$cluster\"} + node_memory_Buffers_bytes{cluster=\"$cluster\"} + node_memory_Cached_bytes{cluster=\"$cluster\"})) / sum by(instance) (node_memory_MemTotal_bytes{cluster=\"$cluster\"})) > 90)\r\n    or 1.0 * sgn(sum by (instance)(node_memory_MemTotal_bytes{cluster=\"$cluster\"} > 0))\r\n    or -1 * sgn(max by (instance) (label_replace(kube_node_info{cluster=\"$cluster\"},\"instance\",\"$1\",\"node\",\"(.*)\")))\r\n,\"_\",\"$1\",\"instance\",\"(.*)\"))\r\n# END inner query\r\n),\"_\",\"Node Memory\", \"\",\"\")",
     "legendFormat": "__auto"
    },
    {
     "expr": "#############################\r\n# Disk Usage Health\r\nlabel_replace(min(\r\n# BEGIN inner query\r\nmin by(node)(label_replace(vector(0)>0\r\n  or 0.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"}) > 10) > 90)\r\n  or 1.0 * sgn(max by(instance) (100 - (100 * node_filesystem_avail_bytes{cluster=\"$cluster\"} \r\n            / node_filesystem_size_bytes{cluster=\"$cluster\"})))\r\n,\"node\",\"$1\",\"instance\",\"(.*)\"))\r\nor max by (node) (kube_node_info{cluster=\"$cluster\"}) * -1 # Baseline by node\r\n# END inner query\r\n),\"_\",\"Node Disk\", \"\",\"\")",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 38 },
     "repeat": "cluster",
     "options": {
      "content": "<div style=\"background-color:#C1C9D1; text-align: center\"> \n  <span style=\"color:black; font-size:16px\">Connectors</span>\n</div>\n\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Connector (OPC-UA) Assets and DataPoints [$cluster]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 40 },
     "repeat": "cluster",
     "targets": [
      {
       "expr": "sum by(_)(\r\n    label_replace(\r\n        aio_opc_asset_count{cluster='$cluster'}\r\n    ,'_','assets','','')\r\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by(_)(\r\n    label_replace(\r\n        aio_opc_asset_datapoint_count{cluster='$cluster'}\r\n    ,'_','datapoints','','')\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": " ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 39 },
     "repeat": "cluster",
     "options": {
      "content": "<div style=\"background-color:#C1C9D1; text-align: center\"> \n  <span style=\"color:black; font-size:16px\">Broker</span>\n</div>\n\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Broker Connected Sessions [$cluster]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "repeat": "cluster",
     "targets": [
      {
       "expr": "sum by(_)(\r\n    label_replace(\r\n        aio_broker_connected_sessions{cluster='$cluster'}\r\n    ,'_','sessions','','')\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Broker Publishes Received by Category [$cluster]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 46 },
     "repeat": "cluster",
     "targets": [
      {
       "expr": "sum by(_)(\r\n    label_replace(\r\n        increase(aio_broker_publishes_received{cluster='$cluster',category!=''}[$__rate_interval])\r\n    ,'_',' $1','category','(.*)')\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Broker Publishes Sent by Category [$cluster]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 51 },
     "repeat": "cluster",
     "targets": [
      {
       "expr": "sum by(_)(\r\n    label_replace(\r\n        increase(aio_broker_publishes_sent{cluster='$cluster',category!=''}[$__rate_interval])\r\n    ,'_',' $1','category','(.*)')\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": " ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
     "repeat": "cluster",
     "options": {
      "content": "<div style=\"background-color:#C1C9D1; text-align: center\"> \n  <span style=\"color:black; font-size:16px\">Dataflows</span>\n</div>\n\n"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Dataflows Messages Received by EndPointType and DataflowId [$cluster]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
     "repeat": "cluster",
     "targets": [
      {
       "expr": "sum by(_)(\r\n    label_replace(label_join(\r\n        increase(aio_dataflow_messages_received{cluster='$cluster'}[5m:1m]),\r\n    '_',',','endpointtype','dataflowid'),'_','received ($1) $2','_','^(.*),(.*)$')\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Dataflows Messages Sent by EndPointType and DataflowId [$cluster]",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
     "repeat": "cluster",
     "targets": [
      {
       "expr": "sum by(_)(\r\n    label_replace(label_join(\r\n        increase(aio_dataflow_messages_sent{cluster='$cluster'}[5m:1m]),\r\n    '_',',','endpointtype','dataflowid'),'_','sent ($1) $2','_','^(.*),(.*)$')\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}