{
 "title": "MQ Broker",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 2, "w": 15, "x": 0, "y": 0 },
   "options": {
    "content": "The MQ metrics documentation can be found here: [MQ metrics](https://learn.microsoft.com/en-us/azure/iot-operations/reference/observability-metrics-mq)\n"
   }
  },
  {
   "title": "Inbound messages / s",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_mq_publishes_received_total{pod_type=\"FE\"}[$__rate_interval]))",
     "legendFormat": "Inbound messages / s"
    }
   ]
  },
  {
   "title": "Outbound messages / s",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_mq_publishes_sent_total{pod_type=\"FE\"}[$__rate_interval]))",
     "legendFormat": "Outbound messages / s"
    }
   ]
  },
  {
   "title": "Topic subscriptions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aio_mq_total_subscriptions{pod_type=\"FE\"})",
     "legendFormat": "Topic subscriptions"
    }
   ]
  },
  {
   "title": "Connected sessions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aio_mq_connected_sessions{hostname=~\".*frontend.*\"})",
     "legendFormat": "Connected sessions"
    }
   ]
  },
  {
   "title": "Ping Health [%] (Avg)",
   "type": "stat",
   "description": "Ping health represents the health of the E4K broker. It is calculated as an average value of ping operation status for each attempt.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(aio_mq_ping_correctness)", "legendFormat": "Health" }
   ]
  },
  {
   "title": "Messages published from Azure IoT MQ to Azure Event Hubs. (10m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(aio_mq_kafka_cloud_publishes_sent_total[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mesages published per 10m",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_mq_kafka_cloud_publishes_sent_total[10m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ping Health [%] (Avg) per route",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "aio_mq_ping_correctness{route!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Counts QoS0 messages dropped",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aio_mq_qos0_messages_dropped_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of retained messages",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aio_mq_store_retained_messages{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KBs of messages retained in the system",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aio_mq_store_retained_bytes{}) / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg ping latency [ms] (99th pctl) Control Chart",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "aio_mq_ping_latency_mu_ms", "legendFormat": "Mean" },
    {
     "expr": "aio_mq_ping_latency_mu_ms - aio_mq_ping_latency_sigma_ms",
     "legendFormat": "1 Std Dev"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms - 2*aio_mq_ping_latency_sigma_ms",
     "legendFormat": "2 Std Dev"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms - 3*aio_mq_ping_latency_sigma_ms",
     "legendFormat": "LCL"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms + aio_mq_ping_latency_sigma_ms",
     "legendFormat": "1 Std Dev"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms + 2*aio_mq_ping_latency_sigma_ms",
     "legendFormat": "2 Std Dev"
    },
    {
     "expr": "aio_mq_ping_latency_mu_ms + 3*aio_mq_ping_latency_sigma_ms",
     "legendFormat": "UCL"
    },
    {
     "expr": "aio_mq_ping_latency_last_value_ms",
     "legendFormat": "Last"
    }
   ]
  }
 ]
}