{
 "title": "OPC UA Broker Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Supervisor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MQTT Publish Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(sum(rate(aio_opc_mqtt_message_publishing_duration_count{service_name=~\"^.*supervisor$\", aio_opc_mqtt_publish_result=\"Success\"}[$__rate_interval])) * 100) / sum(rate(aio_opc_mqtt_message_publishing_duration_count{service_name=~\"^.*supervisor$\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(aio_opc_endpoint_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Thread Pool Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(service_name) (process_runtime_dotnet_thread_pool_threads_count{job=~\"^.*supervisor$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors and Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\", level=~\"ERROR|WARN\"} | json | resources_service_name =~ `^.*supervisor$` | line_format `{{.body}}`"
    }
   ]
  },
  {
   "title": "MQTT Publish Result Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_mqtt_publish_result) (rate(aio_opc_mqtt_message_publishing_duration_count{service_name=~\"^.*supervisor$\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Assets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(aio_opc_asset_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Thread Pool Queue Length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(job) (process_runtime_dotnet_thread_pool_queue_length{service_name=~\"^.*supervisor$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Publishing Latency P95 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_opc_mqtt_message_publishing_duration_bucket{service_name=~\"^.*supervisor$\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Publishing Latency P99 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(aio_opc_mqtt_message_publishing_duration_bucket{service_name=~\"^.*supervisor$\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "OPC UA Connector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "application" },
  {
   "title": "MQTT Publish Success Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_opc_mqtt_message_publishing_duration_count{service_name=~\"^.*connector-sidecar$\", aio_opc_mqtt_publish_result=\"Success\"}[$__rate_interval])) / sum(rate(aio_opc_mqtt_message_publishing_duration_count{service_name=~\"^.*connector-sidecar$\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Changes per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_opc_asset_telemetry_data_change_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connector Thread Pool Thread Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (process_runtime_dotnet_thread_pool_threads_count{service_name=~\"^.*opcua-connector$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors and Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "{exporter=\"OTLP\", level=~\"ERROR|WARN\"} | json | line_format `{{.body}}` | resources_service_name =~ `^.*connector-sidecar$|^.*opcua-connector$`"
    }
   ]
  },
  {
   "title": "MQTT Publish Result Code Distribution",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_mqtt_publish_result) (rate(aio_opc_mqtt_message_publishing_duration_count{service_name=~\"^.*connector-sidecar$\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Value Changes per Second",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(aio_opc_asset_telemetry_value_change_count_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connector Thread Pool Queue Length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (process_runtime_dotnet_thread_pool_queue_length{service_name=~\"^.*opcua-connector$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Publishing Latency P95 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_opc_mqtt_message_publishing_duration_bucket{service_name=~\"^.*connector-sidecar$\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Change Processing Latency P95 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_opc_data_change_processing_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidecar Thread Pool Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (process_runtime_dotnet_thread_pool_threads_count{service_name=~\"^.*connector-sidecar$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Queue Overflow Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(aio_opc_asset_telemetry_value_change_count_total{aio_opc_value_change_status=\"localOverride\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT Publishing Latency P99 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(aio_opc_mqtt_message_publishing_duration_bucket{service_name=~\"^.*connector-sidecar$\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Event Processing Latency P95 [ms]",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(aio_opc_event_processing_duration_milliseconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidecar Thread Pool Queue Length",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (process_runtime_dotnet_thread_pool_queue_length{service_name=~\"^.*connector-sidecar$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(aio_opc_module_name) (aio_opc_output_queue_count)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}