{
 "title": "Resource usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cpu_cores", "query": "4" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node memory usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_node_memory_usage_bytes/(k8s_node_memory_available_bytes+k8s_node_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k8s_node_cpu_time_seconds_total[$__rate_interval]))/$cpu_cores",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node filesystem usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_node_filesystem_usage_bytes/(k8s_node_filesystem_available_bytes + k8s_node_filesystem_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Node memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "k8s_node_memory_usage_bytes/(k8s_node_memory_available_bytes + k8s_node_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node memory used vs available",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k8s_node_memory_available_bytes",
     "legendFormat": "Available memory for node {{k8s_node_name}}"
    },
    {
     "expr": "k8s_node_memory_usage_bytes",
     "legendFormat": "Used memory for node {{k8s_node_name}}"
    }
   ]
  },
  {
   "title": "Pods with the highest memory utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(10, avg(k8s_pod_memory_usage_bytes) by (k8s_pod_name))",
     "legendFormat": "{{process_command}}"
    }
   ]
  },
  { "title": "CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Node CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_node_cpu_time_seconds_total[$__rate_interval])) by (k8s_node_name) / $cpu_cores",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods with the highest CPU utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(10, avg(k8s_pod_cpu_utilization_ratio) by (k8s_pod_name))",
     "legendFormat": "{{process_command}}"
    }
   ]
  },
  {
   "title": "AIO components resource usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "AIO OPC pods CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(k8s_pod_cpu_utilization_ratio{ k8s_pod_name =~ \"aio-opc.*\" }) by (k8s_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AIO OPC pods memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(k8s_pod_memory_usage_bytes{ k8s_pod_name =~ \"aio-opc.*\" }) by (k8s_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AIO MQ pods CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(k8s_pod_cpu_utilization_ratio{ k8s_pod_name =~ \"aio-mq.*\" }) by (k8s_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AIO MQ pods memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(k8s_pod_memory_usage_bytes{ k8s_pod_name =~ \"aio-mq.*\" }) by (k8s_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AIO orchestrators pods CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(k8s_pod_cpu_utilization_ratio{ k8s_pod_name =~ \"aio-orc.*\" }) by (k8s_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AIO orchestrator pods memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(k8s_pod_memory_usage_bytes{ k8s_pod_name =~ \"aio-orc.*\" }) by (k8s_pod_name)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}