apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 6h
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 6h
  releaseName: grafana
  targetNamespace: edge-observability
  chart:
    spec:
      chart: grafana
      version: 7.0.2
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-server.edge-observability.svc.cluster.local
            isDefault: true
            jsonData:
              timeInterval: interval_to_be_overwritten
          - name: Tempo
            type: tempo
            url: http://grafana-tempo.edge-observability.svc.cluster.local:3100
          - name: Loki
            type: loki
            url: http://grafana-loki.edge-observability.svc.cluster.local:3100
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
          - name: "default"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/default
          - name: "custom-dashboards"
            orgId: 1
            folder: ""
            type: file
            disableDeletion: false
            editable: true
            options:
              path: /var/lib/grafana/dashboards/custom-dashboards
    dashboardsConfigMaps:
      custom-dashboards: "custom-grafana-dashboards"
    dashboards:
      default:
        open-telemetry-collector:
          # Ref: https://grafana.com/dashboards/15983
          gnetId: 15983
          revision: 15
          datasource: Prometheus
        cluster-monitoring:
          # Ref: https://grafana.com/dashboards/18681
          gnetId: 18681
          revision: 4
          datasource: Prometheus
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 150Mi

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-tempo
  namespace: flux-system
spec:
  interval: 6h
  releaseName: grafana-tempo
  targetNamespace: edge-observability
  chart:
    spec:
      chart: tempo
      version: 1.7.0
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    persistence:
      enabled: true
      size: 256Mi
    tempo:
      resources:
        requests:
          cpu: 40m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 580Mi
  # This is a default tempo config generated by the Tempo helm chart with the following overridden values:
  # reporting_enabled: false
  # compaction_window: 5m
  # flush_check_period: 5s
  # max_block_duration: 5m
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: ConfigMap
              name: tempo
              namespace: edge-observability
            patch: |
              - op: replace
                path: /data/tempo.yaml
                value:
                  |
                  multitenancy_enabled: false
                  usage_report:
                    reporting_enabled: false
                  compactor:
                    compaction:
                      block_retention: 24h
                      compaction_window: 5m
                  distributor:
                    receivers:
                      jaeger:
                        protocols:
                          grpc:
                            endpoint: 0.0.0.0:14250
                          thrift_binary:
                            endpoint: 0.0.0.0:6832
                          thrift_compact:
                            endpoint: 0.0.0.0:6831
                          thrift_http:
                            endpoint: 0.0.0.0:14268
                      otlp:
                        protocols:
                          grpc:
                            endpoint: 0.0.0.0:4317
                          http:
                            endpoint: 0.0.0.0:4318
                  ingester:
                    flush_check_period: 5s
                    max_block_duration: 5m
                  server:
                    http_listen_port: 3100
                  storage:
                    trace:
                      backend: local
                      local:
                        path: /var/tempo/traces
                      wal:
                        path: /var/tempo/wal
                  querier:
                    {}
                  query_frontend:
                    {}
                  overrides:
                    per_tenant_override_config: /conf/overrides.yaml

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana-loki
  namespace: flux-system
spec:
  interval: 6h
  releaseName: grafana-loki
  targetNamespace: edge-observability
  chart:
    spec:
      chart: loki
      version: 5.36.3
      interval: 6h
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    loki:
      commonConfig:
        replication_factor: 1
      storage:
        type: 'filesystem'
      auth_enabled: false
    singleBinary:
      replicas: 1
      persistence:
        size: 256Mi
      resources:
        limits:
          cpu: 40m
          memory: 256Mi
        requests:
          cpu: 40m
          memory: 256Mi

    test:
      enabled: false
    monitoring:
      dashboards:
        enabled: false
      rules:
        enabled: false
      serviceMonitor:
        enabled: false
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
      lokiCanary:
        enabled: false
    gateway:
      enabled: false
