name: Create git tag
on: 
  push:
    branches: 
      - main
  
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  Build-Code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@8a84c306953900f3c70294cc05f1fbe665d4ba0a # v3.0.3
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@8a84c306953900f3c70294cc05f1fbe665d4ba0a # v3.0.3
      with:
        useConfigFile: true
    - name: Create git tag
      run: |
        git tag ${{ env.GitVersion_MajorMinorPatch }}
      if: github.ref == 'refs/heads/main'
    - name: Push git tag
      run: git push origin ${{ env.GitVersion_MajorMinorPatch }}
      if: github.ref == 'refs/heads/main'