name: Create git tag
on: 
  push:
    branches: 
      - main
  
permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  Build-Code:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@0ad7bfbfd1988727907373a39f29154117ea5205 # v3.0.2
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@0ad7bfbfd1988727907373a39f29154117ea5205 # v3.0.2
      with:
        useConfigFile: true
    - name: Create git tag
      run: |
        git tag ${{ env.GitVersion_MajorMinorPatch }}
      if: github.ref == 'refs/heads/main'
    - name: Push git tag
      run: git push origin ${{ env.GitVersion_MajorMinorPatch }}
      if: github.ref == 'refs/heads/main'